FirstMVCApp/Models/DogViewModel.cs
namespace FirstMVCApp.Models
{
    public class DogViewModel
    {
        public string Name { get; set; }

        public int Age { get; set; }
    }
}

FirstMVCApp/Models/ErrorViewModel.cs
namespace FirstMVCApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FirstMVCApp/Models/PersonViewModel.cs
namespace FirstMVCApp.Models
{
    public class PersonViewModel
    {
        public string Name { get; set; }

        public int Age { get; set; }
    }
}

FirstMVCApp/Controllers/DaddyAPIController.cs
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FirstMVCApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class DaddyAPIController : ControllerBase
    {
        [HttpGet]
        [Route("WhoIsYourDaddy")]
        public string GetWhoIsYourDaddy()
        {
            return "Kenny D";
        }

        [HttpGet]
        [Route("WhoIsYourDaddyCodingClass")]
        public DaddyClass GetWhoIsYourDaddyCodingClass()
        {
            DaddyClass d = new DaddyClass("Ken");
            d.LastName = "Dudley";
            d.TodaysDate = DateTime.Now;
            return d;
        }

        // GET: api/<DaddyAPIController>
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<DaddyAPIController>/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<DaddyAPIController>
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT api/<DaddyAPIController>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/<DaddyAPIController>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

public class DaddyClass
{
    // TYPE ctor tab to get a default constructor
    public DaddyClass(string? firstname)
    {
            this.Firstname = firstname; 
    }

    // type prop tab to get these
    public string? Firstname { get; set; }
    public string? LastName { get; set; }
    public DateTime TodaysDate { get; set; } = DateTime.Now; // this is a default

    public override string ToString()
    {
        return this.Firstname + " " + this.LastName; // string representation of the class 
    }
}

FirstMVCApp/Controllers/HelloWorldController.cs
using FirstMVCApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCApp.Controllers
{
    public class HelloWorldController : Controller
    {
        //add static for new element 
        private static List<PersonViewModel> people = new List<PersonViewModel>();
        public IActionResult Index()
        {
            //PersonViewModel person = new PersonViewModel() 
          //{ Name = "Ryan", Age=22 };
            return View(people);

        }
        //This Iaction method returns the form using PersonViewModel it creates a new form everytime you hit submit 
        public IActionResult Create()
        {
            var personVm = new PersonViewModel();
            return View(personVm);

        }
        //Sends data to CreateForm 
        //This Iaction gets called when you submit the form 
        public IActionResult CreateForm(PersonViewModel personViewModel) 
        {
            
            people.Add(personViewModel);
            return RedirectToAction(nameof(Index));
        
        }
        public string Hello()
        {
            return "Hello Ryan!";
        }

           
    }
}

FirstMVCApp/Controllers/HomeController.cs
using FirstMVCApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FirstMVCApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FirstMVCApp/Views/HelloWorld/Create.cshtml
@model PersonViewModel
<h1>Create</h1>

<hr />

<div class="row">
    <div class="col-6">

        <div class="card">
            <!-- form format-->
            <div class="card-header">
                <h5>Create a new form</h5>
            </div>

            <div class="card-body">
                <form asp-controller="HelloWorld" asp-action="CreateForm" method="post">

                    <div class="mb-3">
                        <label class="form-label">Name</label>
                        <input asp-for=Name type="text" class="form-control" />
                    </div>
                    <div class="mb-3"> 
                        <label class="form-label">Age</label>
                        <input asp-for=Age type="number" class="form-control" />
                    </div>

                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Save</button>

                    </div>

                </form>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
</div>

FirstMVCApp/Views/HelloWorld/Index.cshtml
@model List<FirstMVCApp.Models.PersonViewModel>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Hello World!!!!!!!</h1>
<p>Hello people this is Ryan!</p>
<!--Creates list-->


<ul>
    @foreach(var person in Model){
        <li>@person.Name (@person.Age)</li>

}

</ul>

FirstMVCApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FirstMVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstMVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstMVCApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="HelloWorld" asp-action="Index">Ryan's Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Index">Hello World!</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Create">Create New</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FirstMVCApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>